// apps/nextjs-basic-example/src/components/BlockerNode.tsx
"use client";

/**
 * BlockerNode — a handle-free node that acts as a pure obstacle.
 * No edges connect to it; it exists solely so the router knows
 * to route edges around it.
 */

import { memo } from "react";
import { type NodeProps } from "@xyflow/react";

function BlockerNodeComponent({ data }: NodeProps) {
  return (
    <div
      style={{
        width: 140,
        height: 60,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "#f1f5f9",
        border: "1.5px dashed #94a3b8",
        borderRadius: 8,
        fontSize: 12,
        fontFamily: "sans-serif",
        color: "#64748b",
      }}
    >
      {data.label as string}
    </div>
  );
}

export const BlockerNode = memo(BlockerNodeComponent);

// apps/example-svelte/src/lib/components/BlockerNode.svelte
<!--
  BlockerNode — a handle-free node that acts as a pure obstacle.
  No edges connect to it; it exists solely so the router knows
  to route edges around it.
-->
<script lang="ts">
  let { data } = $props();
</script>

<div class="blocker-node">
  {data.label}
</div>

<style>
  .blocker-node {
    width: 140px;
    height: 60px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: #f1f5f9;
    border: 1.5px dashed #94a3b8;
    border-radius: 8px;
    font-size: 12px;
    font-family: sans-serif;
    color: #64748b;
  }
</style>
