// apps/sveltekit-basic-example/src/lib/components/RoutedEdge.svelte
<!--
  RoutedEdge — custom edge using the routing store for obstacle-avoiding paths.
  Matches the Next.js basic example RoutedEdge.
-->
<script lang="ts">
  import { BaseEdge } from "@xyflow/svelte";
  import { edgeRoutingStore, computeRoutedEdgePath } from "svelteflow-edge-routing";

  let {
    id, source, target, sourceX, sourceY, targetX, targetY,
    sourcePosition, targetPosition, selected = false, markerEnd,
  }: any = $props();

  let result = $derived.by(() => {
    const store = $edgeRoutingStore;
    const [path, , , wasRouted] = computeRoutedEdgePath(
      { id, source, target, sourceX, sourceY, targetX, targetY, sourcePosition, targetPosition, borderRadius: 8, connectorType: "orthogonal" },
      store.routes, store.draggingNodeIds,
    );
    return { path, wasRouted };
  });
</script>

<BaseEdge
  {id}
  path={result.path}
  {markerEnd}
  style="stroke: {selected ? '#2563eb' : '#94a3b8'}; stroke-width: {selected ? 2.5 : 1.5}; stroke-linecap: round; stroke-linejoin: round; {result.wasRouted ? '' : 'stroke-dasharray: 12 4;'}"
/>

// apps/nextjs-basic-example/src/components/RoutedEdge.tsx
"use client";

import { memo } from "react";
import { BaseEdge, type EdgeProps } from "@xyflow/react";
import { useRoutedEdgePath } from "reactflow-edge-routing";

function RoutedEdgeComponent({
  id,
  source,
  target,
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  selected,
  markerEnd,
}: EdgeProps) {
  const [edgePath, , , wasRouted] = useRoutedEdgePath({
    id,
    source,
    target,
    sourceX,
    sourceY,
    targetX,
    targetY,
    sourcePosition,
    targetPosition,
    borderRadius: 8,
    connectorType: "orthogonal",
  });

  return (
    <BaseEdge
      id={id}
      path={edgePath}
      markerEnd={markerEnd}
      style={{
        stroke: selected ? "#2563eb" : wasRouted ? "#94a3b8" : "#94a3b8",
        strokeWidth: selected ? 2.5 : 1.5,
        strokeLinecap: "round",
        strokeLinejoin: "round",
        strokeDasharray: wasRouted ? undefined : "12 4",
      }}
    />
  );
}

export const RoutedEdge = memo(RoutedEdgeComponent);
